<?php
/*
 * This file is part of the YesWeHack BugBounty backend
 *
 * (c) Romain Honel <romain.honel@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Picoss\YousignBundle\Yousign;

use Yousign\Authentication as BaseAuthentication;

/**
 * Class Authentication
 *
 * @author Romain Honel <romain.honel@gmail.com>
 */
class Authentication extends BaseAuthentication
{
    /**
     * {@inheritdoc}
     */
    public function __construct($apikey, $username = null, $password = null)
    {
        if (null !== $password) {
            $password = self::buildHashedPassword($password);
        }

        parent::__construct($apikey, $username, $password);
    }

    /**
     * {@inheritdoc}
     */
    public function setPassword($password, $hash = true)
    {
        if (true == $hash) {
            $password = self::buildHashedPassword($password);
        }

        parent::setPassword($password); // TODO: Change the autogenerated stub
    }
}